### ISSUE TITLE
You need to redo this tutorial lol

### ISSUE THREAD

**Issue by pixelfairee** [PrincessAkira/road-to-yuzu-without-switch#12]
I really appreciate the writeup and the time you took to make this. But this is awful. Instructions leading to selections that don't exist. The title of the tutorial is one thing but then you spend most of the guide instructing us on arbitrary features of yuzu like controller and profile setup? How are these and the proceeding steps necessary? What does this have to do with obtaining prod/title keys without owning a switch? And your gif? What is that? Its just you resizing a window. I'm so confused.

**Comment by Fabian42** [comment]
The GIF just tells you to resize the name column, which is huge by default. It's also not relevant for starting anything, but useful, I guess.

**Comment by Kedwright** [comment]
@pixelfairee Hey friend, I was actually struggling with this earlier and after some digging, I found out that you need to copy all of that text into a file. **BUT** instead of saving it with a ".txt" extension, you want to save it as a ".keys" extension. The finished file should be "prod.keys." After doing this, the error message that you get when booting up yuzu should disappear. 
Hope this helps!

**Comment by toastofchaos** [comment]
> @pixelfairee Hey friend, I was actually struggling with this earlier and after some digging, I found out that you need to copy all of that text into a file. **BUT** instead of saving it with a ".txt" extension, you want to save it as a ".keys" extension. The finished file should be "prod.keys." After doing this, the error message that you get when booting up yuzu should disappear.
> Hope this helps!

I believe doing this got rid of one of the error messages. So to copy all of that text from the link into a file, I first made a text file. I'm wondering if that's part of why I'm still seeing an error message. I need to find a way to always show file extensions in windows.
