### ISSUE TITLE
Keys

### ISSUE THREAD

**Issue by HerXayah** [PrincessAkira/road-to-yuzu-without-switch#3]
I need someone to get me keys, since subreddit is banned. 
If a new key releases please send it here or to me on discord

**Comment by Elohimuel** [comment]
PLEASE READ THIS BEFORE YOU TAKE THIS FILE AT THE BOTTOM OF THIS POST....

EVEN THE VAULT SAID, IT IS DANGEROUS TO GO ALONE, TAKE THIS.

titlekeys.ovh reference - the last of the Wii U before Nintendo shuts the gates or the Enzu ninjas.

The only way your subreddit could have been banned is if they were doing something they were not supposed to be doing with leaks or spoliers. Though technically would not be right if it was a support line.

I want to hold them all accountable or the people who caused the junk before hand like Dark Umbra and Vampa and them and did not give us people at one point a chance to use our devices without being stuck through each to every provider and much forced arrangements as a false EULA agreement. Japan and software developers did not make the device alone yet took credit from coders and other people though Nintendo is American idea.

Perhaps this will solve your issue and others. Part of the reason why Nintendo or Enzu Corporation wants to be a pain is developer sector and they have the authority to do so. I warned them and told them about the switch and what they did, those cloud providers to developers, plus holding people accountable that we should be able to just fix our machine. The vault is to be protected as well.

So in the meantime the sub-redits or communities be banned because they would just copy the code or rig it of the wii originally to DSI or some emulation be more advanced because of code. From the user perspective each one of us wants to code. The only problem here, is that is not productive and it is region based. So, if you just want the keys or new ones, they are really auto generated from the firm to much. 

I don't know if this file will help you or not. Yes, if the encrypted side comes from the states, I told them guard the vault of the WiiU. I even said the switch developers are to be held accountable for ripping users off to the public knows they need a chance to have access rights.

But perhaps this file will help you. I  Just want to know how to input the firmware is all I want to do. Cause mainly you cannot emulate the switch without the firm setup or developer information offered through switch discord which is a pain cause you know most are just unsettled to begin with which is why the emulator will not work and will work for others.

It is called the SDK or files able to run the game to begin with or the proper format.

Technically with the switch any device can be fixed but you have no encryption security with that of Smea and the developers doing what they are doing or some who built it. Also the emulator with it for all associated platforms including wii to 3ds. They should just make a simple homebrew if they wanted to do that for client side rather than one region censor the rest or people building their own devices. 

Everyone builds for themselves pretty much is what the corporation did to user who said we could not play games which was actually the corporate heads. 

If the users did not cheat with leaked releases because of the developers having a dark past and the games being spoiled this argument would not have occurred with me though some point people have to be brave and offer the tough question. When did the government become an antipiracy corporation to that of an entertainment industry as offered though China and Germany to axis powers.

Should the developers or users be held accountable, and my goal was to make them accountable though it could lead to the altercation - aka = developers compared to the average user who needs to enjoy it. 

The cloud administration will care on this one, but is a serious matter as related to the product in China and or other countries which were agreements of an elder issue. So it takes a person honest to admit this. Apple and Google are censoring the public with other media networks.

The ones doing the leaks or testing on the public are the developers themselves to those of us just want to enjoy the games we get and not be set up in some position where we have to offer help to them and or cheat with abandonware and freeware protocol for which is at one point opensource material with copyright patent among a bunch of shareholders with separate code.

Because you asked... I can only offer what is found. I do not own a switch, but because Nintendo refuses to support old devices or the devices are unfinished... we have a serious issue though Nintendo tries to keep cheaters and public at bay, it is the developers who caused the gates to open and shut. So in the in run, it will be to hold each one of us responsible with the code for what is those of us who owned a device originally made.

Using a backup manager one can just autogenerate their own keys to many programs.
I told them, you use the switch... it is direct, I told them - you use the 3ds that is encryption, I told them, you use the wii or wiiU, that is access. Right now it is guarded by the states to a risk of China being a censorship nation and we are not happy or most of us. So, for those who provide leaks it is important to know that if you ask, you will get a direct support. They tried to get rid of much, and that is the first mistake.

Should the cloud providers be happy, that is their choice on what they do but we all know where the argument provided here will lead if a company goes out from one region and censors the rest to other regions that build the protocol to begin with. That will be chaotic which is to avoid at much cost to a point.

So you have people like me who offer a support line, rather than steal an account like a developer or rouge person. We find what we find and we build not to hack but rather just enjoy what is offered.
Every generation needs a chance so I am willing to provide what can be found here compared to splitting much up though it is required to keep a code base.

Other developers will help at some point, but it is not recommended as many receive strange remarks for taking code to others who actually built the software or made the code work.

Apple and Google, their online reference support line, was in fact Nintendo or linked to the corporation. As provided through main domain address. Which is in fact an American company to Japan at one point. So, expect them to come back to the states and get the tech rights back for many of us regular users.

That may or may not solve recent issues but it is they need to quit arguing among themselves and come to some agreement here or work on this. So we offer the support or some of us not knowing what the heck were they thinking - the people or myself.

[yuzu byTheHERO268.zip](https://github.com/PrincessAkira/road-to-yuzu-without-switch/files/4584930/yuzu.byTheHERO268.zip)

**Comment by PrincessAkira** [comment]
what?

**Comment by Elohimuel** [comment]
You asked for the keys, here you go. There is a lot of information people should know in how to build and about Cloud service providers. So for the sake of development, I am sparing this information. I do not blame any particular person, yet want others to build as I once did with the DSI. 

There was something I did as a kid though it required the code of others to the accurate programming. The original way to work the emulator to the hardware source was already given. People should build from scratch, would sound like a good idea to a point of what is needed for others to enjoy it for themselves. As to get your switch keys, you need the hardware to code.

So what is the format and structure of link is in fact the DSI, to Wii, to WiiU, and switch protocol. It is in fact owned through shared providers whose host is down, so one cannot complain aside from what is mentioned in this case as I once helped build from scratch as a kid, but it was a school assignment so I could not take credit for any code used. I was not a coder, but a compiler through a test subject.

Others have rights to enhance the code. But I offer much advice here and it could lead to a legal bit.
I know about who to talk to relating to these matters or what is found. For much at stake. We try to just enjoy what is provided without the hassle though this is for those of us who want to enjoy the work to play the games.

As far as the axis is concerned, the US really has been denied of what it actually owns or has rights to like others should have a right of much. For any complaints you may contact if this person is still available to others who perhaps knew the vault of the Nintendo IP address. As whoever visits the links of a certain page has direct access to the vault because the IP of the cloud providers given can be traced by the folder. So it shows information from who put it out there or where it came.

The leaks came from the corporation, so it begins with the head to that of many more down the line to be responsible. This is what I hold each accountable for that affected people like me down the line. Maybe then, there will be a stable system of management. Though this could be worldwide issue based on hardware parts with testing. If on hand you are developing direct access there should be a situation. This with the hacking of Nintendo accounts thus for the cancelation of services as relating to their news presented on another site that was abandoned by the common public as myself.

So to avoid a lot of hassle. Nintendo has to trace the source of its own company to others to guard their reputation. But that is not strictly possible, because it was owned by cloud providers who provide internet services. So yes they have authority but no they do not have the right for censoring others then putting the blame on someone but themselves. So if you were a developer you are held to a higher standard I believe.

Here is why the switch developers will be in a lot of trouble to that of many more unless the consoles are provided or guarded fair from machine to machine. So this information is here regarding legality to copyright claims.

Whoever owned it first, that is who offers it to and from. Unless there are separate vaults.
Germany has access to the vault of the US corporation, thereby I am here to present this information of legality to you and your region and others for much of what may occur if much is not guarded or protected. 

The direct machine address is traced to the US on the folder vault. As represented by this information. The host does not respond to pings because the host was taken down.
Therefore any information relating to this is connected to other vaults.

inetnum:        5.180.24.0 - 5.180.25.255
netname:        Enzu-5-180
descr:          Enzu cloud and colocation services
country:        US
org:            ORG-EI65-RIPE
admin-c:        NR4287-RIPE
tech-c:         NR4287-RIPE
status:         ASSIGNED PA
mnt-by:         mnt-lv-a1-1
mnt-by:         mnt-us-enzuinc-eu-1
created:        2019-08-26T17:04:40Z
last-modified:  2019-10-29T12:33:40Z
source:         RIPE

organisation:   ORG-EI65-RIPE
org-name:       ENZU Inc.
phone:          +1 (702) 965 1615
org-type:       OTHER
address:        10120 S Eastern Ave, # 248 Henderson, NV 89052, USA
abuse-c:        ACRO26551-RIPE
mnt-ref:        mnt-lv-a1-1
mnt-by:         mnt-lv-a1-1
created:        2019-08-21T09:31:27Z
last-modified:  2019-08-26T16:50:20Z
source:         RIPE # Filtered

person:         Nick Rose
address:        10120 S Eastern Ave # 248
address:        89052
address:        Henderson
address:        UNITED STATES
phone:          +1 (702) 965 1615
nic-hdl:        NR4287-RIPE
mnt-by:         mnt-us-enzuinc-eu-1
created:        2019-09-24T11:32:17Z
last-modified:  2019-09-24T11:32:18Z
source:         RIPE

You may contact Apple and ask what they have to do against Cydia or a developer IOS situation.
I wanted to ask them this legal question but currently there have been bad ethics from other cheats.
As their domain server connects to Nintendo.

It is not to cheat in games, but enjoy the services.

I will be responsible for holding this code, cause whoever has the WIIU database online from GitHub, leaked it the vault. Legality concerning this issue represents a serious issue.
As relating to the hardware it is quite different what others do with it.

America (not as a whole) to other regions or Nintendo corporation is highly responsible for censorship to research methods though they don't want nothing to do with leaks as this coming from their own hand. I think it is an important concept here to let people as yourself enjoy what is given when others of us have to pay for it then get cut off for a subscription. 

It makes no sense to the public as myself. Therefore this is an issue to settle with them or from single region basis based on whoever is talked to about the matter. As it is provided by many shareholders or owners and it is a little late to recover the old, but start with the new.

Because the GQ site was taken down. - Germany has stolen from the US vault.
Because the GQ site was taken down. - There is Europe security with the UK,
Because the US site was obviously hosted, there is a legal issue though the device cannot be pinged.
Because corporate Japan or someone wants to take credit for development that is the software company developers. - I am sorry, to the axis powers on this. But Nintendo was made corporate America and Japan and I wanted to straighten that issue up with developers unless you built the code and it came some of it the code from Russia and or much of a place while others had to wait or chose to develop elsewhere.

**Comment by Elohimuel** [comment]
Nintendo strictly unless it offers censorship against others hopefully is not a part of influential China to some reference of Japan as this could go beyond region to the Asian countries for who actually had a piece of the corporation agreement or title deed.

**Comment by Elohimuel** [comment]
THE IP ADRESSES TAKEN DOWN, proves in fact NINTENDO IS A COMPANY MADE IN AMERICA.
Though most of the corporation hosts much of its parts now in China.

IP address: | 104.129.56.137
-- | --
hostname: | 104.129.56.137.static.quadranet.com
ISP: | QuadraNet
City: | Los Angeles
Region: | California
Country: | United States (US)
Postal code: | 90014
Area code: | 213
Metro code: | 803
latitude: | 34.0494
longitude: | -118.2641

**Comment by Elohimuel** [comment]
Best thing and advice I could give to myself is develop from scratch.

By accessing the this site unless you are from my region or so one to more are in violation of situation standards as provided by protocals of the company and leaking games before they were made available. People enjoy games for a reason though the arguments among spoilers happen with others.

Really I cannot complain here because I am evaluating this as research as to why there is a lot of legal issue in relation to what others had done in the past. 

And that is an elder issue for them to handle. It is not my place to handle each region but rather my own person.

Truely the Nintendo Update Servers are hosted in Japan JNUS and Germany.
But it is in fact an American company. Though the corporate head is to be held accountable to an extent of what they do in a public domain to that of others who offer machines.

**Comment by kqrdiva** [comment]
[Here](https://github.com/kqrdiva/switch_dump), I found some keys, and made them into yuzu format using python.
